// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface Vm {
    function ffi(string[] calldata) external returns (bytes memory);
    function pauseGasMetering() external;
    function resumeGasMetering() external;
    function envOr(string calldata name, string calldata defaultValue) external returns (string memory);
    function envOr(string calldata name, uint256 defaultValue) external returns (uint256);
}

/// @title Poseidon gas benchmark: Fe (readable code) vs iden3 (JS-generated bytecode)
/// @notice The iden3 PoseidonT3 cannot be written in Solidity — it is generated as
/// raw EVM bytecode by poseidon_gencontract.js.  The Fe version is ~90 lines of
/// readable code producing the same results.
contract PoseidonBenchTest {
    address private constant HEVM_ADDRESS = address(uint160(uint256(keccak256("hevm cheat code"))));
    Vm private constant vm = Vm(HEVM_ADDRESS);

    address private feAddr;
    address private iden3Addr;

    function setUp() public {
        vm.pauseGasMetering();

        // Deploy Fe Poseidon
        uint256 optLevel = vm.envOr("FE_SONA_OPT_LEVEL", uint256(0));
        string[] memory cmd = new string[](7);
        cmd[0] = vm.envOr("FE_BIN", "fe");
        cmd[1] = "build";
        cmd[2] = "--backend";
        cmd[3] = "sonatina";
        cmd[4] = "-O";
        cmd[5] = optLevel == 0 ? "0" : optLevel == 1 ? "1" : "2";
        cmd[6] = "fe";
        vm.ffi(cmd);

        string[] memory readCmd = new string[](3);
        readCmd[0] = "bash";
        readCmd[1] = "-c";
        readCmd[2] = "printf '0x'; tr -d '\\n' < fe/out/PoseidonBench.bin";
        bytes memory feInitcode = vm.ffi(readCmd);
        address _fe;
        assembly { _fe := create(0, add(feInitcode, 0x20), mload(feInitcode)) }
        require(_fe != address(0), "Fe deploy failed");
        feAddr = _fe;

        // Deploy iden3 PoseidonT3 (JS-generated bytecode)
        readCmd[2] = "printf '0x'; cat PoseidonT3.hex";
        bytes memory iden3Initcode = vm.ffi(readCmd);
        address _iden3;
        assembly { _iden3 := create(0, add(iden3Initcode, 0x20), mload(iden3Initcode)) }
        require(_iden3 != address(0), "iden3 deploy failed");
        iden3Addr = _iden3;

        vm.resumeGasMetering();
    }

    function test_bothDeploy() public view {
        require(feAddr != address(0), "no Fe");
        require(iden3Addr != address(0), "no iden3");
    }

    /// @notice Verify Fe and iden3 produce identical results for poseidon(1, 2)
    function test_equivalence_1_2() public view {
        uint256 feResult = _callFe(1, 2);
        uint256 iden3Result = _callIden3(1, 2);
        require(feResult == iden3Result, "Fe != iden3");
        require(feResult == 0x115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a, "wrong hash");
    }

    /// @notice Verify equivalence for poseidon(0, 0)
    function test_equivalence_0_0() public view {
        uint256 feResult = _callFe(0, 0);
        uint256 iden3Result = _callIden3(0, 0);
        require(feResult == iden3Result, "Fe != iden3");
        require(feResult == 0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864, "wrong hash");
    }

    /// @notice Gas benchmark: Fe Poseidon
    function testGas_fe_poseidon() public view {
        _callFe(1, 2);
    }

    /// @notice Gas benchmark: iden3 PoseidonT3 (JS-generated bytecode)
    function testGas_iden3_poseidon() public view {
        _callIden3(1, 2);
    }

    function _callFe(uint256 a, uint256 b) internal view returns (uint256) {
        // selector: poseidon(uint256,uint256)
        bytes memory cd = abi.encodeWithSelector(
            bytes4(keccak256("poseidon(uint256,uint256)")), a, b
        );
        (bool ok, bytes memory ret) = feAddr.staticcall(cd);
        require(ok, "Fe call failed");
        return abi.decode(ret, (uint256));
    }

    function _callIden3(uint256 a, uint256 b) internal view returns (uint256) {
        // selector: poseidon(uint256[2])
        (bool ok, bytes memory ret) = iden3Addr.staticcall(
            abi.encodeWithSelector(bytes4(keccak256("poseidon(uint256[2])")), a, b)
        );
        require(ok, "iden3 call failed");
        return abi.decode(ret, (uint256));
    }
}
